import accordionsScss from "./accordions.scss";
import autocompleteScss from "./autocomplete.scss";
import avatarsScss from "./avatars.scss";
import badgesScss from "./badges.scss";
import barsScss from "./bars.scss";
import baseScss from "./base.scss";
import breadcrumbsScss from "./breadcrumbs.scss";
import buttonsScss from "./buttons.scss";
import calendarsScss from "./calendars.scss";
import cardsScss from "./cards.scss";
import carouselsScss from "./carousels.scss";
import chipsScss from "./chips.scss";
import codesScss from "./codes.scss";
import comparisonSlidersScss from "./comparison-sliders.scss";
import dropdownsScss from "./dropdowns.scss";
import emptyScss from "./empty.scss";
import filtersScss from "./filters.scss";
import formsScss from "./forms.scss";
import heroScss from "./hero.scss";
import iconsScss from "./icons.scss";
import labelsScss from "./labels.scss";
import layoutScss from "./layout.scss";
import mediaScss from "./media.scss";
import menusScss from "./menus.scss";
import metersScss from "./meters.scss";
import modalsScss from "./modals.scss";
import navbarScss from "./navbar.scss";
import navsScss from "./navs.scss";
import normalizeScss from "./normalize.scss";
import offCanvasScss from "./off-canvas.scss";
import paginationScss from "./pagination.scss";
import panelsScss from "./panels.scss";
import parallaxScss from "./parallax.scss";
import popoversScss from "./popovers.scss";
import progressScss from "./progress.scss";
import slidersScss from "./sliders.scss";
import stylesScss from "./styles.scss";
import stepsScss from "./steps.scss";
import tablesScss from "./tables.scss";
import tabsScss from "./tabs.scss";
import tilesScss from "./tiles.scss";
import timelinesScss from "./timelines.scss";
import toastsScss from "./toasts.scss";
import tooltipsScss from "./tooltips.scss";
import typographyScss from "./typography.scss";
import utilitiesScss from "./utilities.scss";
import viewer360Scss from "./viewer-360.scss";

export const JsxStyle = ({ styles }) => (
  <style jsx global>
    {styles}
  </style>
);

export const AccordionsStyles = () => <JsxStyle styles={accordionsScss} />;
export const AutocompleteStyles = () => <JsxStyle styles={autocompleteScss} />;
export const AvatarsStyles = () => <JsxStyle styles={avatarsScss} />;
export const BadgesStyles = () => <JsxStyle styles={badgesScss} />;
export const BarsStyles = () => <JsxStyle styles={barsScss} />;
export const BaseStyles = () => <JsxStyle styles={baseScss} />;
export const BreadcrumbsStyles = () => <JsxStyle styles={breadcrumbsScss} />;
export const ButtonsStyles = () => <JsxStyle styles={buttonsScss} />;
export const CalendarsStyles = () => <JsxStyle styles={calendarsScss} />;
export const CardsStyles = () => <JsxStyle styles={cardsScss} />;
export const CarouselsStyles = () => <JsxStyle styles={carouselsScss} />;
export const ChipsStyles = () => <JsxStyle styles={chipsScss} />;
export const CodesStyles = () => <JsxStyle styles={codesScss} />;
export const ComparisonSlidersStyles = () => <JsxStyle styles={comparisonSlidersScss} />;
export const DropdownsStyles = () => <JsxStyle styles={dropdownsScss} />;
export const EmptyStyles = () => <JsxStyle styles={emptyScss} />;
export const FiltersStyles = () => <JsxStyle styles={filtersScss} />;
export const FormsStyles = () => <JsxStyle styles={formsScss} />;
export const HeroStyles = () => <JsxStyle styles={heroScss} />;
export const IconsStyles = () => <JsxStyle styles={iconsScss} />;
export const LabelsStyles = () => <JsxStyle styles={labelsScss} />;
export const LayoutStyles = () => <JsxStyle styles={layoutScss} />;
export const MediaStyles = () => <JsxStyle styles={mediaScss} />;
export const MenusStyles = () => <JsxStyle styles={menusScss} />;
export const MetersStyles = () => <JsxStyle styles={metersScss} />;
export const ModalsStyles = () => <JsxStyle styles={modalsScss} />;
export const NavbarStyles = () => <JsxStyle styles={navbarScss} />;
export const NavsStyles = () => <JsxStyle styles={navsScss} />;
export const NormalizeStyles = () => <JsxStyle styles={normalizeScss} />;
export const OffCanvasStyles = () => <JsxStyle styles={offCanvasScss} />;
export const PaginationStyles = () => <JsxStyle styles={paginationScss} />;
export const PanelsStyles = () => <JsxStyle styles={panelsScss} />;
export const ParallaxStyles = () => <JsxStyle styles={parallaxScss} />;
export const PopoversStyles = () => <JsxStyle styles={popoversScss} />;
export const ProgressStyles = () => <JsxStyle styles={progressScss} />;
export const SlidersStyles = () => <JsxStyle styles={slidersScss} />;
export const StylesStyles = () => <JsxStyle styles={stylesScss} />;
export const StepsStyles = () => <JsxStyle styles={stepsScss} />;
export const TablesStyles = () => <JsxStyle styles={tablesScss} />;
export const TabsStyles = () => <JsxStyle styles={tabsScss} />;
export const TilesStyles = () => <JsxStyle styles={tilesScss} />;
export const TimelinesStyles = () => <JsxStyle styles={timelinesScss} />;
export const ToastsStyles = () => <JsxStyle styles={toastsScss} />;
export const TooltipsStyles = () => <JsxStyle styles={tooltipsScss} />;
export const TypographyStyles = () => <JsxStyle styles={typographyScss} />;
export const UtilitiesStyles = () => <JsxStyle styles={utilitiesScss} />;
export const Viewer360Styles = () => <JsxStyle styles={viewer360Scss} />;
